### ISSUE TITLE
Registering and Documenting handler names and arguments

### ISSUE THREAD

**Issue by loppear** [nxus/core#15]
1. `Module.gather` and `Module.respond` should accept a module instance as the handler, and bind the event to `inst[event].bind(inst)`.
  * But this style is probably optional, since it really only benefits the documentation below
2. Modules should use documentation.js and document their public event methods like:
  ```
class Storage {
  constructor (app) {
    app.respond('getModel', this);
  }

  /** Get a model
   * @param modelName
   * @return A Promise of a Waterline model collection instance.
  */
  getModel (modelName) { 
...
  ```

**Comment by mjreich** [comment]
Overall :+1: with a couple of thoughts:

1. Should definitely have an example for usage (e.g. accessing through `respond` rather than directly).
1. I think this is a flavor of having the module register somehow so that emit/on, etc are handled on this rather than through the event delegate:
```
constructor(app) {
  app.get('router').use(this);
}
```
That way we could simplify it to `app.respond('getModel')` and get the extra advantage of cutting out `app.get('router)` for most calls.

Not to add to much to the API, but maybe this is a separate method called `respondWith()`

**Comment by loppear** [comment]
I'm missing how `Module.use(this)` is implemented, did you mean `this.respond('getModel')` in your example :+1:? Clients would still do `app.get('router').request('getModel')`, but I'll all about the removal of `app.get(myself)` repeats.

**Comment by mjreich** [comment]
@loppear no, sorry that was unclear.  `Module.use()` isn't implemented yet, but should be.
