### ISSUE TITLE
core/BaseModule

### ISSUE THREAD

**Issue by mjreich** [nxus/core#43]
Propose a BaseModule we can extend from that does the following things:

1. Sets this.config using BaseModule._configDefaults
1. Sets app.get(this._moduleName).use(this)
1. Sets this.app
1. Auto registers respond/gather based on introspection and a naming convention:
   1. gatherSomeThing -> this.gather('someThing')
   1. respondSomeThing -> this.respond('someThing')

**Comment by loppear** [comment]
:-1: on the auto register based on name, it's a big gain I think that the gather/respond method names *match* the events for documentation, so that `app.get('module').someThing()` corresponds to docs for `module.someThing`. Do you like:
```
class SomeModule extends BaseModule {
  get gathers() {
    return ['someThing']
  }
}
```
that much over:
```
class SomeModule extends BaseModule {
  constructor (app) {
    super(app)
    this.gather('someThing')
  }
}
```

**Comment by loppear** [comment]
As far as config goes, right now we have patterns for implementation-level default config and final application package config, do we want Application to allow intermediate (npm) modules to contribute config as well, is SomeModule's package.json a better place for default config to live than on the implementation class (not sure)? (with _.deepExtend and some tweaks to structure) This could let AdminUI set a default for `adminModel` (`{}`), Users could define config for `admin-ui.adminModel` (`{"user": ...}`), and the final application to add its own adminModel config or override "user", all from their package.jsons rather than in code.
