### ISSUE TITLE
New Module API Proposal for v4

### ISSUE THREAD

**Issue by mjreich** [nxus/core#74]
Thinking about a couple of issues currently:

1. We need to migrate to node v5/6 and npm v3, which means no peer dependencies
1. We need a better module interface. The current API for creating modules requires a lot of lines of code for basic setup, which means a lot of learning to create new modules for essentially boilerplate things.  Our conventions are different than standard design patterns, so there is no 'intuitive' path for new developers.

## Proposed Changes

1. Modules/Application are accessed using ES6 `import` statements, rather than via the `app.get` pattern.  This is implemented through a static `getInstance`.
1. Every module extends a base `NxusModule` class which takes care of auto-binding the module to the module proxy (automatically exposing all public instance methods)
1. Every module has a set of internal lifecycle methods (`_init`, `_startup`, etc) bound to the corresponding application boot stage.
1. Module instantiation moves from the application into the Module itself. The static method `getInstance` creates the ModuleProxy and the Module instance if it hasn’t been declared yet, rather than the application creating a ModuleProxy on access. 
1. An implication of this is that we no longer have un-installed optional modules. E.g. every Module that needs another module would have to have it in the package.json, otherwise `import` will throw an exception.

## Example Uage

```javascript
// Required Modules
import {NxusModule} from 'nxus-core'
import {router} from 'nxus-router'
import {templater} from 'nxus-templater'
import {app} from 'nxus-core'
import {adminUI} from 'nxus-admin-ui'

class MyModule extends NxusModule {
  static Version = '1.0.0' //should match what's in package.json

  constructor(config) { //opts == app.config.MyModule
    super(config) //instantiated on app.load boot stage 
    console.log(this.config) // {someConfig: 'value'}
    router.route('myRoute', (req, res) => {…})
    templater.template('some-template.ejs')
    ….
  }

  _init() {
    //fires on app.init boot stage 
  
  }

  _startup() {
    //fires on app.startup boot stage
  }

  _launch() {
    //fires on app.launch boot stage
  }

  myMethod(vars) {
    //available as MyModule.myMethod()
  }

  _myPrivateMethod(vars) {
    //Not available on MyModule
  }
}

export default MyModule

export var myModule = MyModule.getInstance() // convention to expose the instance as lowercase object {myModule}

```

### v3 vs v4

```javascript
//Nxus v3 style
class Tags { 
  constructor(app) {
    this._app = app
    this._templater = this._app.get('templater')
    this._router = this._app.get('router')

    this._templater.template(__dirname+'/views/tag-page.ejs', 'page')
    this._router.route('/tags/:id', this._index.bind(this))
  }

  _index (req, res) {
    return this._templater.render('tag-page', {title: 'Tag Page'}).then(res.send.bind(res))
  }
}
```
```javascript
// Nxus v4 style
import {NxusModule} from 'nxus-core'
import {application} from 'nxus-core'
import {router} from 'nxus-router'
import {templater} from 'nxus-templater'

class Tags extends NxusModule {
  constructor(config) {
    super(config)

    router.route('/tags/:id', this::_index)
    templater.template(__dirname+'/views/tag-page.ejs', 'page')
  }

  _index(req, res)  {
    return templater.render('tag-page', {title: 'Tag Page'}).then(res::send)
  }
}
```
## Application initialization

Application initialization would need to change, since {Application} will return the current Application instance.

```javascript
import Application from 'nxus-core' //missing the {} brackets

let myApp = new Application({…opts})

myApp.start()

import {application} from 'nxus-core'

console.log(myApp == Application) // true
```

## Implementation

In order to replicate the singleton behavior of the current Nxus, each module will need to expose a global of itself, and check whether that singleton already exists.

```javascript
// Application.js
import ModuleManager from './ModuleManager'
import ModuleProxy from './ModuleProxy'

class Application {
  constructor(opts) {
    global['nxus-modules'] = {}
    this._loadModules()
  }

  _loadModules() {
    var modules = ModuleManager.getModules() //returns top-level modules
    for(module of modules) { 
      console.log(moduleInfo) // {name: 'MyModule', path: '/some/path/to/MyModule/'}
      let moduleClass = require(module.path)
      moduleClass.getInstance() //This will take care of creating the moduleProxy and Instance
    }
  }
}
```

```javascript
// NxusModule.js

import {application} from 'nxus-core'
import {ModuleProxy} from 'nxus-core'

class NxusModule {
  static Version = null //should be overridden by subclasses

  constructor(config) {
    global['nxus-modules'][this.constructor.name].use(this)
  }

  static getInstance() {
    if(!this.Version) throw new Error('Module needs to declare a version')
    if(!global['nxus-modules'][this.constructor.name]) global['nxus-modules'][module.name] = new ModuleProxy(this.constructor.name) // module.instance == false
    if(!global['nxus-modules'][this.constructor.name].instance) {
      new this(application.config[this.constructor.name])
    } else {
      if(global['nxus-modules'][this.constructor.name].version != this.Version) //probably to some SemVer checking here for major version match only, or maybe just patch?
        throw new Warning('Version mismatch.')
    }
    return global['nxus-modules'][this.constructor.name]
  }
}
```
## Open Questions

1. Should the instance be a lowercase return? E.g. `import {application} from 'nxus-core’}`
2. Does npm v3 create a flat hierarchy? If so, how will it handle module version mismatches? And also if so, how does this avoid the version mismatch problem of peerDependencies?
3. And the big question **how do we handle version mismatches?**  The default here throws a warning if there are mismatched versions. However, we could have a Nxus assumption that all minor/patch versions must be equivalent and proceed, etc.  Either way, we need to think about version resolution since npm will no longer do this for us via peerDependencies.
4. Do we want ModuleProxy anymore?  Do we want to find a way to continue having soft dependencies (e.g calling Router.route even if Router isn’t installed)?
    1. We could emulate this through configuration by having a config option `enabled` supported by NxusModule which avoids acting on anything if set to `false`.  This would give us the ability to turn off modules we don’t want to have running in configuration, but still have them available for import.
    1. The answer is probably yes, because ModuleProxy also ensures method calls are resolved at the right point in the application boot cycle.  This is the feature we use the most right now, rather than the dynamic bindings (e.g. no-ops on calls to uninstalled modules)
    1. Also useful for bypassing circular dependencies.  In `getInstance()`, `new this(application.config[this.constructor.name])` could be pushed into nextTick while the moduleProxy is returned and collects the event bindings, etc.

**Comment by ScottMaxson** [comment]
A couple thoughts/questions/suggestions that come to mind reading this through for the first time:

- Overall I'm fine with the convention of overriding a base class and explicitly importing dependent "service" modules; this makes for a more consistent package-handling environment and could/might prevent some bloat of loading modules in Core ( though maybe there isn't any?) as the library of modules grows. I think this does lessen some of the "mystery" of where functionality comes from in building an app.
- A lot of the newbie (and not-so-newbie) confusion can be mitigated by keeping our reference app examples up to date. It's really hard to build anything without base-ui, user, admin, admin-ui, templater, router to start with. The base nxus-example app can include those as an example. Maybe those 6 +/- modules should be offered as a meta-package?
- The last line of your *Application Initialization* example should be ```myApp == application``` I think?
- I'd offer the idea that rather than naming the super class method "getInstance" call it something that connotes the registrar function it's serving; though it can function as a singleton accessor/factory it feels like it's purpose is richer than that?
- I mistrust having to maintain a version# in the code and in the package.json. Is there a good way to have both of those reference a .nxusrc setting or something? I know this might break the way "npm version" works, so perhaps it's too hard....

I can add to this as time/attention permits. Thanks for the thorough thinking/documenting.

**Comment by davidkellerman** [comment]
Overall, I like this design a lot. It feels a lot more conventional, which I think is a good thing.

  * The nxus module versioning mechanism looks ugly to me, but I'm not sure I understand all the issues involved. 
  
  I _think_ the core of it is this: Nxus modules are singleton instances (global, or at least associated with a singleton application instance). All references to a nxus module need to resolve to that single instance, which needs to have a version that's compatible across all the references. This is at cross-purposes to node's nested hierarchy that allows multiple instances and versions of a module to coexist.

    What I'm wondering is this: Doesn't npm give you most of what you need? If I understand correctly, as of v3 it will dedupe module references &ndash; if all dependencies can be satisfied by a single version of a module, you should end up with a single instance in node_modules. So, it's doing all the version reconciliation for you; all you have to do is make sure there's only one instance. It _seems_ like there ought to be a way of doing this that doesn't require putting a version in the nxus module.

  * (re paragraph #5, un-installed optional modules; open question #4) In my experience so far, the way the module proxy keeps a missing module from triggering errors counts more as a bug than a feature. I'm getting quicker at catching it, but there have been multiple times things mysteriously just weren't working, and I eventually realized a module was missing from node_modules, either because I'd forgotten to add it, or because I'd forgotten to reinstall after pulling over an update from Mike.

    It would be nice to retain the proxy's handling of the boot cycle and circular dependencies, but throw errors for missing modules. (It's not that hard to crib together a stub for a module that's not yet implemented.)

  * (re Implementation) It might make sense for NxusModule to delegate the module registration machinery to application. It seems like the global context _belongs_ to the application more than the module. From a practical standpoint, it avoids some problems with multiple co-existing versions of NxusModule, and allows the machinery to be modified without requiring an update to NxusModule and all its subclasses. 

  * (re open question #1) Lowercase. I'm used to uppercase being reserved for class definitions; think that's pretty well-entrenched convention. Similarly, I'd make the NxusModule version be "version," not "Version" (you _could_ argue for "VERSION," since it's a constant).

  * (re open question #4, i) I have had cases where it would have been nice to suppress the automatic loading of top-level modules (e.g. work in progress, development-only, retired modules). Trick is to do it some way that isn't cryptic –– offhand, I can't think of anything better than your config option, plus some logging (e.g. "module x is disabled in configuration and was not loaded").

  * I've really grown to like chaining of method calls. There are many cases in what are typically configuration calls where this would work nicely. For example:
    ```
    let pipeliner = this._app.get('pipeliner')
    pipeliner.pipeline('recipe_build')
    pipeliner.task('recipe_build', 'process', this._addUser)
    pipeliner.task('recipe_build', 'process', this._addRecipe)
    pipeliner.task('recipe_build', 'generate', this._saveRecipeBuildEvent)
    ```
    Would be nicer as:
    ```
    pipeliner.pipeline('recipe_build')
      .task('process', this._addUser)
      .task('process', this._addRecipe)
      .task('generate', this._saveRecipeBuildEvent)
    ```

    I don't know whether something like this is practical, with the way the module proxy wraps everything in promises. Have you given it any thought?

**Comment by loppear** [comment]
Oooh this is a nice big change. Comments and replies:

1. NxusModule base class is definitely :+1: but 
 1. I assume the `constructor(config)` rather than `constructor(app)` change is because application is expected to be imported now. Would config here the global config or the module's config?
 1. I'm not sold on repeating the boot cycle in convenience methods here, how common has generic boot-level stuff become? (e.g. Storage would need it, but needs to make specific `once`/`onceAfter` hooks.)
 1. Not clear how "automatically exposing all public methods" will work, but goal is to remove `gather`/`respond` calls in constructor - I could go either way on this, it's boilerplate-removing for most cases but loses the only semantic declaration we have of what style of event a method is.
1. Versions. npm3 installs in a deduped flat hierarchy, but still supports conflicting versions (in which case they are still installed under).
  1. We require (via peerDep now, indirectly) that there not be version conflicts. That will continue to be true with modules as singletons.
  1. We should rely on npm to handle semver equivalencies and usually get us to one installed version across dependencies.
  1. given above, I don't think we can avoid the possibility of the same "do not proceed" conflict that peerDeps has, but we can delay that to startup and as in the example either warn or stop (I'd vote stop, with config to allow it to go ahead for debugging and fixing)
  1. I do not think modules should re-declare their version (expecting to keep in sync with package.json) - there's surely to be a way for Application to read the installed version from package.json (even if we have to enforce naming conventions for modules), and that's the only place that needs to check it.
1. Uninstalled optional modules
  1. The main place I still want this is when there are optional backends (mongo vs blah), which I guess isn't a nxus module level concern. So the use case is e.g. `admin-ui` doing something based on whether `users` is installed, and I think I'm fine with those always needing to be inverted or requiring a third helper module to be installed (`admin-ui` provides all the hooks, no users-specific implementation - since both treat the other as optional, you'd need an `admin-ui-users` module that hooks them together?)
1. `getInstance` - only concern here is it's boilerplate for modules to forget to export. Would be nice if `NxusModule` could set a static attribute (`this.constructor[this.constructor.name.toLowerCase()] = getInstance()`) but I'll have to refresh my import semantics to remind me whether that's possible in JS.
  1. Could avoid naming question by always naming that attribute `instance` and doing `import {instance as myModule} from MyModule`.

Separate issue: @davidkellerman chaining method calls on `provide` I don't think is directly doable (they're supported now on the `gather` side, fwiw which isn't much) as it's just as common to want to wait for the result via the promise. Might be reasonable to add a `chain()` or other explicit starting method on `Module` to wrap the default return value from subsequent `provide` calls, though we'd have to think it through.

**Comment by loppear** [comment]
Oh yeah, my other wishlist for a NxusModule base class (from #43, which is mostly defunct in light of the import changes in this issue, but also includes some relevant discussion on auto-registering events) is that it have a `defaultConfig()` method that `constructor` calls to do the writeDefaultConfig boilerplate.

**Comment by loppear** [comment]
Open question 4, yes I think we absolutely need ModuleProxy for the lifecycle timing of events (this *could* move to NxusModule, but would still involve a proxy). The implementation of ModuleProxy may become more sane in node6 for having the improved standard ProxyAPI implementation.

I think disabling installed modules via config is a separate issue, but likely worth supporting.

**Comment by mjreich** [comment]
Also, to document: version management is going to happen behind the scenes, with the caveat that all Nxus modules need to be minor version backwards compatible.
