### ISSUE TITLE
Module Organization Proposal

### ISSUE THREAD

**Issue by mjreich** [nxus/core#82]
As part of Nxus 4, we should re-organize/rename modules to better reflect a couple of things we’ve learned:

1. Our current module structure is too monolithic, with lots of disparate functionality in the same module.  This leads to confusion about where things are.  For example, are sessions be in `nxus-router` or in `nxus-users`?
1. Module naming is a little opaque.
1. With the Nxus 4 architecture, we’ll benefit from having `metamodules` that combine multiple individual modules into packages that can be easily included. 

## 'Core' Modules 

```
-nxus-core
  |-nxus-watcher
  |-nxus-logger
  |-nxus-tester
-nxus-storage
  |-nxus-storage-sqlite
  |-nxus-storage-mongo
-nxus-router
  |-nxus-router-sessions
  |-nxus-router-sessions-file
-nxus-templater
  |-nxus-templater-ejs (for helpers like <%- render() %>
-nxus-renderer
  |-nxus-renderer-ejs
-nxus-clientjs
  |-nxus-clientjs-babel
  |-nxus-clientjs-react
-nxus-mailer
  |-nxus-mailer-sendgrid
```

## 'Standard' Metamodules
```
-nxus-web
  |-nxus-default-template
  |-nxus-base-ui
-nxus-admin
  |-nxus-admin-template
  |-nxus-admin-ui
-nxus-users
  |-nxus-user
  |-nxus-team
  |-nxus-authentication
  |-nxus-authorization
  |-nxus-users-admin
  |-nxus-team-admin
  |-nxus-user-profile
```

## 'Contrib' modules
```
-nxus-data
  |-nxus-data-manager
    |-nxus-data-manager-csv
    |-nxus-data-manager-json
  |-nxus-data-magager-admin
-nxus-geo
  |-nxus-geo-model
  |-nxus-maps
…
```

**Comment by loppear** [comment]
Is the proposal that these are all separate packages, or sub-modules packaged together (not exactly the metamodule idea, but then I assume metamodules are just empty packages that have dependencies on their sub real modules?) - If I depend on `nxus-users`, I'm going to get the grouped functionality either way, it appears, so is this about code organization within the nxus-users module?

I'm wary of multiplying out the number of coordinated repos when all our uses so far and going forward would seem to always want to use the feature-ful metamodules.
I'm onboard with the organization here though for reorganizing within the existing packages, esp for the "backend" bits - tying in sendgrid, ejs, etc.

**Comment by mjreich** [comment]
@loppear I’m a bit agnostic, however splitting into separate modules where necessary will be nice.  For example, nxus-router-sessions-file should be replaceable with nxus-router-sessions-mongo.  Whether that’s done in config or via npm is maybe the question.

**Comment by ScottMaxson** [comment]
Wondering if "nxus-templater" and "nxus-renderer" offer separate functionality? What's the split in responsibilities?

**Comment by loppear** [comment]
Agree on motivation for the backend ones - I think it will need to be config in some way, because you're going to want the default/metamodule to install one (-file), and then the application to install another (-mongo) - would rather you didn't need to unpack the meta deps, so having two installed and picking between them will be the norm.

I'm not sure about using 'metamodules' for this actually, vs the other use of them to combine heterogenous packages into a convenient name, but probably moot until we detail what if anything a metamodule is vs just module dependencies.

To the proposed organization:
 * A few of these (`nxus-logger`) would be expected to be imported by other modules and so will need to be split to their own packages if we want to access it that way in v4. The rest are mostly internal and could go either way on being exposed as packages or merely organized within the parent package.
 * Agree on not having a `nxus-renderer` top-level package, `templater` should be the entry point.
 * Not sure about the granularity of `nxus-users` submodules, but I guess half of those are the glue between a base model and admin (again, if the common use is going to be to use the all-in-one parent/meta package anyways...)

**Comment by loppear** [comment]
A step towards supporting sub-modules that will match how we write easy-to-extract-to-their-own-repo-someday project-local modules:

## PluginManager should recurse into a `modules` directory in `nxus-*` modules as well.

so that right now we can refactor e.g. `router` to have `modules/router-sessions` as a full module and no longer expect the parent module to explicitly import and instantiate these (repeat in Renderer, DataManager, etc)

**Comment by loppear** [comment]
Question: dashed vs camelCased names for modules and submodules: per #74, most access to modules will be by initial lower case camel. I don't think we have a case for directly accessing most of these submodules this way (but `routerSessionsFile` would be the proxy variable if so), but I think these do come up in config (currently as dashed - `admin-ui`, `s3-files`) - do we want to leave config names dashed or switch to the lowerCamelCase?

**Comment by loppear** [comment]
Moving these all to be modules helps flatten config (good/bad) - e.g. configuring `router-sessions` to use a backend besides file might be:
```
"router-sessions": {
  "store": "router-sessions-file",
  "settings": {
    "secret": ...,
  }
},
"router-sessions-file": {
  "path": "./tmp/sessions"
}
```
(For switching backends like this, there may still be a case for using app.get() rather than dynamically requiring the appropriate module!)

**Comment by mjreich** [comment]
I vote for following NPMs coding standards (https://docs.npmjs.com/misc/coding-style) specifically:

> ## Case, naming, etc.
> 
> Use lowerCamelCase for multiword identifiers when they refer to objects, functions, methods, properties, or anything not specified in this section.
> 
> Use UpperCamelCase for class names (things that you'd pass to "new").
> 
> Use all-lower-hyphen-css-case for multiword filenames and config keys.
> 
> Use named functions. They make stack traces easier to follow.
> 
> Use CAPS_SNAKE_CASE for constants, things that should never change and are rarely used.
> 
> Use a single uppercase letter for function names where the function would normally be anonymous, but needs to call itself recursively. It makes it clear that it's a "throwaway" function.

**Comment by mjreich** [comment]
@loppear re flattening of config, I'm good with that.  I think it makes a whole lot of things simpler, from defaultConfig writing to overwriting config through ENV variables.

**Comment by mjreich** [comment]
@loppear hrm on recursion.  I guess with npm3 its probably not a bad thing.  We avoided it in the future because of nested dependencies and having no good way to resolve them, but NPM3 does that now so I guess not an issue?

Or are you suggesting only recursing a directory called `modules`?
